## Implementation of perceptron using python

In [17]:
## import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
from matplotlib.colors import ListedColormap

In [18]:
plt.style.use('fivethirtyeight')

In [31]:
class Perceptron:

    def __init__(self, eta, epochs):
      np.random.seed(345)
      self.weights = np.random.randn(3) * 1e-4  ## multiplying by small number to get very small weights
      print(f'Initial weights before training: {self.weights}')
      self.eta = eta
      self.epochs = epochs

    def activationFunction(self, inputs, weights):
      z = np.dot(inputs, weights)
      return np.where(z>0, 1, 0)

    def fit(self, X, y):
      self.X = X
      self.y = y

      X_with_bias = np.c_[self.X, -np.ones((len(self.X),1),dtype='int')] # adding bias term using concatenation opeation
      print(f"X with bias: {X_with_bias}")

      for epoch in range(self.epochs):
        print("--"*10)
        print(f"for epoch: {epoch}")
        print("--"*10)

        ## perdicting the values
        y_hat = self.activationFunction(X_with_bias, self.weights) # forward propogation
        print(f"Predicted value after the forward pass: {y_hat}")

        ## finding the error
        self.error = self.y - y_hat
        print(f"Error: {self.error}\n")

        ## updating the weights
        self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error) # backward propogation
        print(f"Updated weights after epoch {epoch}/{self.epochs}: {self.weights}\n")
        print("####"*10)

    def predict(self, X):
      X_with_bias = np.c_[X, -np.ones((len(X),1))] # adding bias term using concatenation opeation
      return self.activationFunction(X_with_bias, self.weights)

    def total_loss(self):
      total_loss = np.sum(self.error)
      print(f"The total loss is {total_loss}")
      return total_loss

In [32]:
def prepareData(df):
    X = df.drop('y', axis=1)
    y = df['y']
    return X, y

In [33]:
## Creating AND gate as a new dataset

AND = {
    'x1': [0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}

df = pd.DataFrame(AND)

df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [34]:
X, y = prepareData(df)

In [35]:
eta = 0.3
epochs = 10

model = Perceptron(eta, epochs)
model.fit(X, y)

loss = model.total_loss()

Initial weights before training: [ 0.00014692 -0.00011501  0.00025192]
X with bias: [[ 0  0 -1]
 [ 0  1 -1]
 [ 1  0 -1]
 [ 1  1 -1]]
--------------------
for epoch: 0
--------------------
Predicted value after the forward pass: [0 0 0 0]
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64

Updated weights after epoch 0/10: [ 0.30014692  0.29988499 -0.29974808]

########################################
--------------------
for epoch: 1
--------------------
Predicted value after the forward pass: [1 1 1 1]
Error: 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64

Updated weights after epoch 1/10: [ 1.46924823e-04 -1.15014431e-04  6.00251923e-01]

########################################
--------------------
for epoch: 2
--------------------
Predicted value after the forward pass: [0 0 0 0]
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64

Updated weights after epoch 2/10: [0.30014692 0.29988499 0.30025192]

########################################
--------------------
for ep

In [36]:
inputs = np.array([[1,0],[1,1],[0,0]])
model.predict(inputs)

array([0, 1, 0])

In [37]:
## Creating OR gate as a new dataset

OR = {
    'x1': [0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,1]
}

df2 = pd.DataFrame(OR)

df2

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [38]:
X1, y1 = prepareData(df2)

eta = 0.3
epochs = 10

model2 = Perceptron(eta, epochs)
model2.fit(X1, y1)

loss = model2.total_loss()

Initial weights before training: [ 0.00014692 -0.00011501  0.00025192]
X with bias: [[ 0  0 -1]
 [ 0  1 -1]
 [ 1  0 -1]
 [ 1  1 -1]]
--------------------
for epoch: 0
--------------------
Predicted value after the forward pass: [0 0 0 0]
Error: 0    0
1    1
2    1
3    1
Name: y, dtype: int64

Updated weights after epoch 0/10: [ 0.60014692  0.59988499 -0.89974808]

########################################
--------------------
for epoch: 1
--------------------
Predicted value after the forward pass: [1 1 1 1]
Error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64

Updated weights after epoch 1/10: [ 0.60014692  0.59988499 -0.59974808]

########################################
--------------------
for epoch: 2
--------------------
Predicted value after the forward pass: [1 1 1 1]
Error: 0   -1
1    0
2    0
3    0
Name: y, dtype: int64

Updated weights after epoch 2/10: [ 0.60014692  0.59988499 -0.29974808]

########################################
--------------------
for epoch: 3
--

In [39]:
## creating a XOR gate as a new dataset

XOR = {
    'x1': [0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,0]
}

df3 = pd.DataFrame(XOR)

df3

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [44]:
X2, y2 = prepareData(df3)

eta = 0.3
epochs = 100

model3 = Perceptron(eta, epochs)
model3.fit(X2, y2)

loss = model3.total_loss()

Initial weights before training: [ 0.00014692 -0.00011501  0.00025192]
X with bias: [[ 0  0 -1]
 [ 0  1 -1]
 [ 1  0 -1]
 [ 1  1 -1]]
--------------------
for epoch: 0
--------------------
Predicted value after the forward pass: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64

Updated weights after epoch 0/100: [ 0.30014692  0.29988499 -0.59974808]

########################################
--------------------
for epoch: 1
--------------------
Predicted value after the forward pass: [1 1 1 1]
Error: 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64

Updated weights after epoch 1/100: [ 0.00014692 -0.00011501  0.00025192]

########################################
--------------------
for epoch: 2
--------------------
Predicted value after the forward pass: [0 0 0 0]
Error: 0    0
1    1
2    1
3    0
Name: y, dtype: int64

Updated weights after epoch 2/100: [ 0.30014692  0.29988499 -0.59974808]

########################################
--------------------
for epoch: 3

**No matter how much epochs we give for XOR, we are not getting a total loss of zero**

**Perceptron will not be able to find the satisfactory results for the non-linear separation**